// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNXQlEBfD2p1OLFwKsotM9p4Fh4dzRt_A',
    appId: '1:341019569235:web:08e3a13016cfead956aaa6',
    messagingSenderId: '341019569235',
    projectId: 'contadordespertar',
    authDomain: 'contadordespertar.firebaseapp.com',
    storageBucket: 'contadordespertar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR8fPzcap_O4mxchV9vctq64KZear0kFQ',
    appId: '1:341019569235:android:3d1379a29454948156aaa6',
    messagingSenderId: '341019569235',
    projectId: 'contadordespertar',
    storageBucket: 'contadordespertar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpda98bCQZVFJ54-uGluDRj3u2qGKQDUg',
    appId: '1:341019569235:ios:2d154ca65faea8b456aaa6',
    messagingSenderId: '341019569235',
    projectId: 'contadordespertar',
    storageBucket: 'contadordespertar.appspot.com',
    iosBundleId: 'com.example.contadorDespertar',
  );
}
